### ISSUE TITLE
New themes

### ISSUE THREAD

**Issue by kant01ne** [NkxxkN/supertokens-auth-react-themes#5]
Come up with themes dedicated to industries (B2B, B2C, etc...) with good examples to take inspiration from

@makerboiAdi can you take care of that one?

**Comment by makerboiAdi** [comment]
Noted, will do. Do you think we should do this before launch?

**Comment by kant01ne** [comment]
No I don't think this is required for launch. This will be an ongoing project. Not a top priority but more of a nice to have to showcase supertokens.

Adding one to my list:
 - https://app.forestadmin.com/login

Also, should we credit the original somewhere? 🤔 It's not forbidden to copy website layouts but I'm just wondering.

**Comment by kant01ne** [comment]
Closing for now as we have 3 themes to maintain and that's enough for now. Will reopen if needed.

**Comment by makerboiAdi** [comment]
Reopening this for Mufassir to share different themes he is thinking of and to get feedback from us.

 Mufassir, here are two examples to help you get started:
https://app.forestadmin.com/login
https://www.npmjs.com/login

As discussed, please look at different signup UIs in different places and categorize common use cases and share here

Edit: Not sure how to add / tag mufassir here
